### ISSUE TITLE
Need .env file for completely setup

### ISSUE THREAD

**Issue by Abduraxmonnn** [Goldendevsuz/AudioBookAPI#6]
`DEBUG` `SECRET_KEY` `ALLOWED_HOSTS` `DATABASES` list of variables which I need.

**Comment by under-script** [comment]
Assalomu alaykum. Thank you for attention.
[added forgotten key examples as you told.](https://github.com/Goldendevsuz/AudioBookAPI/commit/95c9a90830f32396c4dfce65f73781d3bde665b2)
